import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const $ = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today = new Date();
const dateLabel = value => { if(!value) return "Date to be announced"; const d=new Date(value+"T00:00:00"); return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}); };
const initials = name => String(name||"?").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();
function empty(id,show){$(id).hidden=!show;}
function blank(){return {settings:{clubName:"Nayyouvak Sporting Club Adri",district:"Adri, Mau, Uttar Pradesh",phone:""},players:[],matches:[],fixtures:[],staff:[]};}
function render(raw){
 const data={...blank(),...(raw||{})};data.settings={...blank().settings,...(data.settings||{})};data.players=Array.isArray(data.players)?data.players:[];data.matches=Array.isArray(data.matches)?data.matches:[];data.fixtures=Array.isArray(data.fixtures)?data.fixtures:[];
 const name=data.settings.clubName||"Nayyouvak Sporting Club Adri";
 ["contactName","footerName"].forEach(id=>$(id).textContent=name);$("brandName").textContent=name.toUpperCase();$("heroName").innerHTML=esc(name).replace(/Club Adri/i,"<span>Club Adri</span>");$("districtText").textContent=data.settings.district||"Adri, Mau, Uttar Pradesh";$("phoneText").textContent=data.settings.phone?"Phone: "+data.settings.phone:"Contact details will be published here by the club.";
 const active=data.players.filter(p=>(p.status||"Active")==="Active");$("playerCount").textContent=`${active.length} active ${active.length===1?"player":"players"}`;
 $("playerGrid").innerHTML=active.map(p=>`<article class="player"><div class="avatar">${p.photo?`<img src="${esc(p.photo)}" alt="Photo of ${esc(p.name)}" loading="lazy" onerror="this.parentElement.textContent='${esc(initials(p.name))}'">`:esc(initials(p.name))}</div><h3>${esc(p.name||"Club Player")}</h3><p>${esc(p.position||"Player")}</p><span class="jersey">${p.jersey?"Jersey #"+esc(p.jersey):"Nayyouvak SC"}</span></article>`).join("");empty("playerEmpty",!active.length);
 const upcoming=data.fixtures.filter(f=>f.date && f.date>=today.toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date));
 $("matchCount").textContent=`${upcoming.length} upcoming ${upcoming.length===1?"match":"matches"}`;
 $("matchGrid").innerHTML=upcoming.map(f=>{const picked=(f.playerIds||[]).map(id=>active.find(p=>p.id===id)).filter(Boolean);return `<article class="card match-card"><span class="match-tag">⚽ ${esc(f.status||"SQUAD ANNOUNCED")}</span><h3>Nayyouvak SC vs ${esc(f.opponent||"Opponent TBA")}</h3><p>📅 ${esc(dateLabel(f.date))}${f.time?" · 🕒 "+esc(f.time):""}</p><p>📍 ${esc(f.venue||"Venue to be announced")}</p>${f.tournament?`<p>🏆 ${esc(f.tournament)}</p>`:""}<div class="meta">${f.reportTime?`<span>⏰ Report ${esc(f.reportTime)}</span>`:""}<span>👥 ${picked.length||((f.playerIds||[]).length)} selected players</span></div>${picked.length?`<p style="margin-top:12px"><strong>Playing squad:</strong> ${picked.map(p=>esc(p.name)).join(", ")}</p>`:""}</article>`;}).join("");empty("matchEmpty",!upcoming.length);
 const galleryItems=[];const teamImg="assets/images/teamm.png";galleryItems.push({src:teamImg,alt:"Nayyouvak Sporting Club team"});active.forEach(p=>{if(p.photo)galleryItems.push({src:p.photo,alt:p.name||"Club player"})});$("galleryGrid").innerHTML=galleryItems.map(x=>`<div class="photo"><img src="${esc(x.src)}" alt="${esc(x.alt)}" loading="lazy"></div>`).join("");empty("galleryEmpty",!galleryItems.length);
 const played=data.matches.filter(m=>m.status==="Played").length;const future=upcoming.length;const highlights=[{icon:"👥",title:"Squad Together",body:`${active.length} active player${active.length===1?"":"s"} currently listed in the club roster.`},{icon:"📅",title:"Next Fixtures",body:future?`${future} upcoming match${future===1?"":"es"} published for supporters and players.`:"New match fixtures will appear here after the club publishes them."},{icon:"🏟️",title:"Match History",body:played?`${played} completed match${played===1?"":"es"} recorded in the club portal.`:"Club match results will be shared here when results are recorded."}];$("highlightGrid").innerHTML=highlights.map(h=>`<article class="feature"><div class="feature-icon">${h.icon}</div><h3>${h.title}</h3><p>${h.body}</p></article>`).join("");
 const notices=upcoming.slice(0,5).map(f=>({icon:"📣",title:"Upcoming match: "+(f.opponent||"Opponent to be announced"),body:`${dateLabel(f.date)}${f.time?" at "+f.time:""} · ${f.venue||"Venue to be announced"}${f.tournament?" · "+f.tournament:""}`}));$("noticeList").innerHTML=notices.map(n=>`<article class="notice"><div class="notice-icon">${n.icon}</div><div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div></article>`).join("");empty("noticeEmpty",!notices.length);
 $("dataStatus").textContent="Public club information · Financial records and private player details are not displayed.";
}
$("year").textContent=new Date().getFullYear();$("menuBtn").addEventListener("click",()=>$("nav").classList.toggle("open"));document.querySelectorAll("#nav a").forEach(a=>a.addEventListener("click",()=>$("nav").classList.remove("open")));
async function start(){
 let rendered=false;
 try { if(firebaseConfig.apiKey && firebaseConfig.projectId){const app=initializeApp(firebaseConfig);const db=getFirestore(app);const snap=await getDoc(doc(db,"club","public"));if(snap.exists()){render(snap.data());rendered=true;$("dataStatus").textContent="Live public club data loaded from Firebase. Private finances and sensitive player details are excluded.";}else{$("dataStatus").textContent="Public club data has not been published yet. Showing available local preview, if any.";}} }catch(err){console.warn("Public Firebase read unavailable:",err);$("dataStatus").textContent="Could not load live data. Showing this browser's saved preview, if available. Check Firebase public read rules and hosting connection.";}
 if(!rendered){try{const local=JSON.parse(localStorage.getItem("nsc_adri_management_v1")||"null");render(local||blank());}catch{render(blank());}}
}
start();
